[picojvm] Add picoJSE text and utility helpers

diff --git a/picojc/Makefile b/picojc/Makefile
--- a/picojc/Makefile
+++ b/picojc/Makefile
@@ -352,7 +352,32 @@ test-disk-picojse-io: $(PICOJVM) $(BUILDDIR)/picojc-disk.pjvm
 		false; \
 	fi
 
-test-disk-picojse: test-disk-picojse-term test-disk-picojse-io
+test-disk-picojse-std: $(PICOJVM) $(BUILDDIR)/picojc-disk.pjvm
+	@mkdir -p $(BUILDDIR)/disk_picojse_std
+	@cp $(PICOJSE_DIR)/Native.java $(BUILDDIR)/disk_picojse_std/
+	@cp $(PICOJSE_DIR)/io/Binary.java $(BUILDDIR)/disk_picojse_std/
+	@cp $(PICOJSE_DIR)/util/Bytes.java $(BUILDDIR)/disk_picojse_std/
+	@cp $(PICOJSE_DIR)/util/Ints.java $(BUILDDIR)/disk_picojse_std/
+	@cp $(PICOJSE_DIR)/text/Format.java $(BUILDDIR)/disk_picojse_std/
+	@cp $(PICOJSE_DIR)/text/Parse.java $(BUILDDIR)/disk_picojse_std/
+	@cp $(PICOJSE_DIR)/text/Strings.java $(BUILDDIR)/disk_picojse_std/
+	@cp $(PICOJSE_TESTDIR)/PicoJseStdSmoke.java $(BUILDDIR)/disk_picojse_std/
+	@printf 'Native.java\nBinary.java\nBytes.java\nInts.java\nFormat.java\nParse.java\nStrings.java\nPicoJseStdSmoke.java\n' > $(BUILDDIR)/disk_picojse_std/sources.lst
+	@echo "--- picoJSE StdSmoke (disk package) ---"
+	@cd $(BUILDDIR)/disk_picojse_std && $(DISK_PICOJVM) $(DISK_COMPILER) > PicoJseStdSmoke.pjvm \
+		2> PicoJseStdSmoke_compile.log
+	@$(PICOJVM) $(BUILDDIR)/disk_picojse_std/PicoJseStdSmoke.pjvm > $(BUILDDIR)/disk_picojse_std/PicoJseStdSmoke.out \
+		2> $(BUILDDIR)/disk_picojse_std/PicoJseStdSmoke_run.log || true
+	@if diff -q $(BUILDDIR)/disk_picojse_std/PicoJseStdSmoke.out $(EXPDIR)/PicoJseStd.txt > /dev/null 2>&1; then \
+		echo "PASS: picoJSE StdSmoke (disk package)"; \
+	else \
+		echo "FAIL: picoJSE StdSmoke (disk package)"; \
+		echo "  Expected:"; cat $(EXPDIR)/PicoJseStd.txt | head -8; \
+		echo "  Got:"; cat $(BUILDDIR)/disk_picojse_std/PicoJseStdSmoke.out | head -8; \
+		false; \
+	fi
+
+test-disk-picojse: test-disk-picojse-term test-disk-picojse-io test-disk-picojse-std
 
 # Disk selfhost: compile compiler sources via sources.lst, verify byte-identical to memory mode
 test-disk-selfhost: $(PICOJVM) $(BUILDDIR)/picojc-disk.pjvm $(BUILDDIR)/gen1.pjvm
@@ -490,7 +515,7 @@ test-all: test test-negative test-selfhost test-disk test-disk-multi test-disk-p
 clean:
 	rm -rf $(BUILDDIR)
 
-.PHONY: all test test-negative test-all build check-javac clean test-disk test-disk-multi test-disk-package test-disk-picojse test-disk-picojse-term test-disk-picojse-io test-disk-selfhost
+.PHONY: all test test-negative test-all build check-javac clean test-disk test-disk-multi test-disk-package test-disk-picojse test-disk-picojse-term test-disk-picojse-io test-disk-picojse-std test-disk-selfhost
 .PHONY: test-selfhost test-selfhost-fixpoint test-binmatch test-gen1
 .PRECIOUS: $(BUILDDIR)/%.pjvm $(BUILDDIR)/%.out
 .PRECIOUS: $(BUILDDIR)/gen1_%.pjvm $(BUILDDIR)/gen1_%.out
